-- ============================================================================
-- Mizys CRM — MÓDULO 5 (insumos) e MARGEM ALVO
--
-- Rode uma vez no SQL Editor do Supabase. É idempotente: rodar duas vezes não
-- quebra nada e não duplica os materiais de exemplo.
--
-- O que entra:
--   1. `materiais`  — o catálogo de uniforme, EPI, material de limpeza e exames
--   2. `propostas.materiais`    — os insumos escolhidos em cada proposta
--   3. `propostas.margem_alvo`  — a margem líquida desejada, em %
--
-- Por que insumo não é equipamento: equipamento é bem durável e o valor cheio
-- cai todo mês. Insumo é reposição — o que importa é o PRAZO DE TROCA. Um
-- conjunto de uniforme de R$ 190 trocado a cada 6 meses custa R$ 31,67 por
-- funcionário por mês, e é isso que tem que entrar no custo direto, não R$ 190.
-- ============================================================================

create table if not exists materiais (
  id bigint generated by default as identity primary key,
  nome text not null,
  -- Só rótulo, para agrupar na tela. Não muda conta nenhuma.
  categoria text not null default 'Material',
  unidade text not null default 'un',
  -- Valor de AQUISIÇÃO de uma unidade, não o custo mensal.
  valor numeric(12,2) not null default 0,
  -- De quantos em quantos meses se repõe. 1 = todo mês; 6 = duas vezes ao ano.
  -- O custo mensal é valor ÷ meses.
  meses integer not null default 1 check (meses >= 1),
  -- Por quanto multiplicar. Errar aqui é o jeito mais rápido de orçar uniforme
  -- para 3 pessoas num contrato que tem 14: o fator de cobertura faz o
  -- headcount ser bem maior que o número de postos.
  --   funcionario · uniforme, EPI, exame       → × nº de funcionários
  --   posto       · rádio, chave, livro        → × nº de postos
  --   contrato    · produto da área comum      → × 1
  base text not null default 'funcionario'
    check (base in ('funcionario','posto','contrato')),
  obs text,
  ativo boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists materiais_nome_idx on materiais (lower(nome));

-- `materiais` na proposta: [{ "id": 3, "qtd": 2 }]  — qtd é por BASE do
-- material (2 conjuntos de uniforme POR FUNCIONÁRIO, não 2 no total).
alter table propostas add column if not exists materiais jsonb not null default '[]';

-- Margem líquida desejada, em %. Preenchida, ela manda no lucro de planilha:
-- o motor resolve L = (1−T) ÷ [((1−T) − m) × (1−d)] − 1. Zero = o vendedor
-- digita o lucro de planilha à mão, como antes.
alter table propostas add column if not exists margem_alvo numeric(8,4) not null default 0;

-- ── triggers ────────────────────────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'tg_touch_materiais') then
    create trigger tg_touch_materiais before update on materiais
      for each row execute function tg_touch();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'tg_audit_materiais') then
    create trigger tg_audit_materiais after insert or update or delete on materiais
      for each row execute function tg_auditoria();
  end if;
end $$;

-- ── RLS: catálogo — todo autenticado lê, só admin/gestor escreve ────────────
alter table materiais enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies
                 where tablename = 'materiais' and policyname = 'materiais_ler') then
    create policy "materiais_ler" on materiais for select to authenticated using (true);
    create policy "materiais_inserir" on materiais for insert to authenticated
      with check (app_pode_gerir());
    create policy "materiais_editar" on materiais for update to authenticated
      using (app_pode_gerir()) with check (app_pode_gerir());
    create policy "materiais_apagar" on materiais for delete to authenticated
      using (app_pode_gerir());
  end if;
end $$;

-- ── catálogo inicial ────────────────────────────────────────────────────────
-- Valores de referência do mercado de facilities em SP, 2026. Ajuste pelos
-- seus. O que importa aqui é o PRAZO: é ele que transforma a compra anual em
-- custo mensal.
insert into materiais (nome, categoria, unidade, valor, meses, base, obs)
select * from (values
  ('Conjunto de uniforme',        'Uniforme', 'conj', 190.00,  6, 'funcionario',
   'Calça e camisa. CCT do asseio em SP manda 2 conjuntos por ano.'),
  ('Calçado de segurança',        'EPI',      'par',   95.00, 12, 'funcionario',
   'CA obrigatório. Troca anual ou por desgaste.'),
  ('Kit de EPI (luva, óculos, máscara)', 'EPI', 'kit',  48.00,  3, 'funcionario',
   'Reposição trimestral. Luva nitrílica é o item que mais sai.'),
  ('Crachá e porta-crachá',       'Uniforme', 'un',     18.00, 12, 'funcionario', null),
  ('Exame admissional e periódico','Exames',  'un',    130.00, 12, 'funcionario',
   'ASO periódico anual. O admissional entra no primeiro mês e dilui no prazo.'),
  ('Material de limpeza — cota mensal', 'Material', 'cota', 320.00, 1, 'contrato',
   'Produto, pano, saco de lixo. Cota fechada por contrato, não por pessoa.'),
  ('Rádio comunicador',           'Equipagem','un',    240.00, 24, 'posto',
   'Um por posto, não por funcionário: o rádio fica no posto e troca de mão.'),
  ('Livro de ocorrência',         'Equipagem','un',     35.00,  6, 'posto', null)
) as v(nome, categoria, unidade, valor, meses, base, obs)
where not exists (select 1 from materiais);

-- ── margem: sem valor padrão ────────────────────────────────────────────────
-- A margem alvo nasce VAZIA em cada proposta, de propósito: campo
-- pré-preenchido com número plausível é aceito sem ser olhado, e margem é
-- decisão comercial de cada contrato, não configuração de sistema. Quem manda
-- na tela é `proposta_margem_minima`, que já existe e é só informativo.
--
-- Este delete existe para quem chegou a rodar a primeira versão deste arquivo,
-- que criava uma `proposta_margem_alvo` com 12,5 — ela não é mais lida por
-- ninguém, e config que não faz nada é pior do que config nenhuma.
delete from configuracoes where chave = 'proposta_margem_alvo';

update configuracoes
   set descricao = 'Lucro de planilha padrão (%) — markup sobre o custo, usado só quando não há margem alvo'
 where chave = 'proposta_markup';

-- ── conferência ─────────────────────────────────────────────────────────────
select 'materiais' as tabela, count(*) as linhas from materiais
union all
select 'propostas.materiais', count(*) from information_schema.columns
 where table_name = 'propostas' and column_name = 'materiais'
union all
select 'propostas.margem_alvo', count(*) from information_schema.columns
 where table_name = 'propostas' and column_name = 'margem_alvo';
